#!/usr/bin/env bash
# Loop from 1 to 10, displaying "bad luck" for the 4th iteration,
# "good luck" for the 8th iteration, and "Best School", otherwise.

i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]
	then
		echo bad luck
	elif [ $i = 8 ]
	then
	        echo good luck
	else
		echo Best School
	fi
	((i++))
done
